# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  #schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  #push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🦑 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes
          plugin_achievements_secrets: yes    

      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}   
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          #output_action: gist
          #committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_discussions: yes  

      - name: 🦑 Other stuff
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@dd64c50bf38be91795e73980f3483d028e7e55ee
        with:
          filename: other.svg
          token: ${{ secrets.METRICS_TOKEN }}   
          base: header
          base_indepth: yes
          #output_action: gist
          #committer_gist: ${{ secrets.GIST }}
          plugin_lines: yes
          plugin_traffic: yes
          
          
